name: Continuous Integration
on: [push]
jobs:

  pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    name: lint, test & build
    env:
      ENVIRONMENT: ci
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run lint, test & build
        run: make lint && make test && make build

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: test and tag
    env:
      ENVIRONMENT: ci
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run release
        run: make release && ./scripts/ci/tag.sh
